<?php
	include('conn.php');
	
	$id=$_GET['id'];
	
	$SERVICERECIEVED=$_POST['SERVICERECIEVED'];
	$FOLLOWUPDATE=$_POST['FOLLOWUPDATE'];
	$CAPTUREDBY=$_POST['CAPTUREDBY']; 
	$FOLLOWUPLAN=$_POST['FOLLOWUPLAN'];
	$CONTACTADDRESS=$_POST['CONTACTADDRESS'];
	$CONTACTPERSON=$_POST['CONTACTPERSON'];
	$SERVICEREFERREDFOR=$_POST['SERVICEREFERREDFOR'];
	$MEDICALREFERRAL=$_POST['MEDICALREFERRAL'];
	$CLIENTCONTACT=$_POST['CLIENTCONTACT'];
	$PLACEOFRESIDENCE=$_POST['PLACEOFRESIDENCE'];  
	$SEX=$_POST['SEX'];
	$AGE1=$_POST['AGE1'];
	$CLIENTNAME=$_POST['CLIENTNAME'];  
	$DATECREATED=$_POST['DATECREATED'];
	$NTIHCNO=$_POST['NTIHCNO'];
	$REFTUNER=$_POST['REFTUNER'];
	
	
	mysqli_query($conn,"update referral set SERVICERECIEVED='$SERVICERECIEVED',  
	                                        FOLLOWUPLAN='$FOLLOWUPLAN', 
											CONTACTADDRESS='$CONTACTADDRESS', 
											CONTACTPERSON='$CONTACTPERSON', 
											SERVICEREFERREDFOR='$SERVICEREFERREDFOR', 
											MEDICALREFERRAL='$MEDICALREFERRAL', 
											CLIENTCONTACT='$CLIENTCONTACT', 
											PLACEOFRESIDENCE='$PLACEOFRESIDENCE', 
	                                        SEX='$SEX', 
											AGE1='$AGE1', 
											CLIENTNAME='$CLIENTNAME', 
											DATECREATED='$DATECREATED', 
											NTIHCNO='$NTIHCNO',  
	                                        FOLLOWUPDATE='$FOLLOWUPDATE',  
											REFTUNER='$REFTUNER',  
											CAPTUREDBY='$CAPTUREDBY' 
	where RID='$id'");
	header('location:index.php');

?>