 
<?php
$servername = "localhost";
$username = "root";
$password = "toor2";
$dbname = "patientmgt";

if(isset($_POST['CLIENTNAME'])){
// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);

// Check connection
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
   }

  $sql1 ="SELECT id FROM antenatalcare  ORDER BY id DESC LIMIT 1";
  $NO ='0';
  if($result1 = mysqli_query($conn, $sql1)){
            while($row = mysqli_fetch_array($result1)){
			       $NO= ''.(intval($row['id'])) ;
					 }
					 }


$NTIHCNO = trim($_POST['NTIHCNO']); 
$DATECREATED = trim($_POST['DATECREATED']);
$CLIENTNAME = trim($_POST['CLIENTNAME']); 
$SCHOOLINGSTATUS = trim($_POST['SCHOOLINGSTATUS']);
$AGE = trim($_POST['AGE']);
$DATEOFBIRTH = trim($_POST['DATEOFBIRTH']);
$AGE_GROUP = trim($_POST['AGE_GROUP']);
 
$PHONECONTACT    = trim($_POST['PHONECONTACT']); 
$HEALTHUNIT    = trim($_POST['HEALTHUNIT']); 

$LCONE = trim($_POST['LCONE']); 
$CARDIACDISEASE = trim($_POST['CARDIACDISEASE']);
$KIDNEYDISEASE = trim($_POST['KIDNEYDISEASE']); 
$VILLAGE    = trim($_POST['VILLAGE']);  
$PARISH = trim($_POST['PARISH']);
$HYPERTENSION = trim($_POST['HYPERTENSION']); 
$TB = trim($_POST['TB']);
$CLIENTOCCUPATION = trim($_POST['CLIENTOCCUPATION']); 
$RELIGION    = trim($_POST['RELIGION']); 
$ASTHMA    = trim($_POST['ASTHMA']); 
$TRIBE = trim($_POST['TRIBE']); 
$STI = trim($_POST['STI']);
$SICKLECELLS = trim($_POST['SICKLECELLS']); 
$MARITALSTATUS    = trim($_POST['MARITALSTATUS']);   
$EPILEPSYTWO    = trim($_POST['EPILEPSYTWO']);

$BLEEDINGTWO = trim($_POST['BLEEDINGTWO']); 
$NEXTOFKIN = trim($_POST['NEXTOFKIN']);
$NEXTOFKINCONTACT = trim($_POST['NEXTOFKINCONTACT']); 
$NEXTOFKINRELATIONSHIP    = trim($_POST['NEXTOFKINRELATIONSHIP']);  
$OCCUPATION = trim($_POST['OCCUPATION']);
$OPERATIONS = trim($_POST['OPERATIONS']); 
$BLOODTRANSFUSION = trim($_POST['BLOODTRANSFUSION']);
$ADDRESS = trim($_POST['ADDRESS']); 
$REASONFORBLOODTRANSFUSION    = trim($_POST['REASONFORBLOODTRANSFUSION']); 
$GRAVIDA    = trim($_POST['GRAVIDA']); 
$PARA = trim($_POST['PARA']); 
$ABORTIONS = trim($_POST['ABORTIONS']);
$FRACTURES = trim($_POST['FRACTURES']); 
$DC    = trim($_POST['DC']);   
$ECTOPICPREGNANCY    = trim($_POST['ECTOPICPREGNANCY']); 

$CAESAREANSECTION = trim($_POST['CAESAREANSECTION']); 
$VACUUMSXTRACTION = trim($_POST['VACUUMSXTRACTION']);
$MENSES = trim($_POST['MENSES']); 
$AMOUNT    = trim($_POST['AMOUNT']);  
$RETAINEDPLACENTA = trim($_POST['RETAINEDPLACENTA']);
$PPH = trim($_POST['PPH']); 
$METHODEVERUSED = trim($_POST['METHODEVERUSED']);
$DISCONTINUEDATE = trim($_POST['DISCONTINUEDATE']); 
$OPERATIONSONTHEUTERUS    = trim($_POST['OPERATIONSONTHEUTERUS']); 
$CERVICALCIRCLAGE    = trim($_POST['CERVICALCIRCLAGE']); 
$REASONFORDISCONTINUE = trim($_POST['REASONFORDISCONTINUE']); 
$REASONFORNEVERATTEMPT = trim($_POST['REASONFORNEVERATTEMPT']);
$SMOKING = trim($_POST['SMOKING']); 
$ALCOHOL    = trim($_POST['ALCOHOL']);   
$HEALTHOFTHEHUSBAND    = trim($_POST['HEALTHOFTHEHUSBAND']);
$FIRSTDAYOFLNMP    = trim($_POST['FIRSTDAYOFLNMP']); 

$EDD = trim($_POST['EDD']); 
$GENSTATIONPERIOD = trim($_POST['GENSTATIONPERIOD']);
$PREGNANCYCOMPLICATION = trim($_POST['PREGNANCYCOMPLICATION']); 
$DIABETESTWO    = trim($_POST['DIABETESTWO']);  
$HYPERTENSIONTWO = trim($_POST['HYPERTENSIONTWO']);
$HOSPITALIZATIONTWO = trim($_POST['HOSPITALIZATIONTWO']); 
$HOSPITALIZATIONFOR = trim($_POST['HOSPITALIZATIONFOR']);
$BLEEDING = trim($_POST['BLEEDING']); 
$SICKLECELLSTWO    = trim($_POST['SICKLECELLSTWO']); 
$EPILEPSY    = trim($_POST['EPILEPSY']); 
$EXCESSIVEVOMITING = trim($_POST['EXCESSIVEVOMITING']); 
$HUSBANDSHEALTH = trim($_POST['HUSBANDSHEALTH']);
$FEVER = trim($_POST['FEVER']); 
$DIARRHOEA    = trim($_POST['DIARRHOEA']);   
$COUGH    = trim($_POST['COUGH']);
$WEIGHTLOSS    = trim($_POST['WEIGHTLOSS']);
$OTHERS    = trim($_POST['OTHERS']);  

 
$KNOWSTATUS = trim($_POST['KNOWSTATUS']); 
$WANTTOTEST = trim($_POST['WANTTOTEST']);
$HEIGHT = trim($_POST['HEIGHT']); 
$WEIGHT    = trim($_POST['WEIGHT']);  
$BP = trim($_POST['BP']);
$PULSE = trim($_POST['PULSE']); 
$TEMPERATURE = trim($_POST['TEMPERATURE']);
$NUTRITIONALSTATUS = trim($_POST['NUTRITIONALSTATUS']); 
$WT    = trim($_POST['WT']); 
$MUAC    = trim($_POST['MUAC']); 
$ORALTHRUSH = trim($_POST['ORALTHRUSH']); 
$ANAEMIA = trim($_POST['ANAEMIA']);
$TEETH = trim($_POST['TEETH']); 
$EYES    = trim($_POST['EYES']);   
$NECK    = trim($_POST['NECK']);
$NAILS    = trim($_POST['NAILS']);
$BREASTS    = trim($_POST['BREASTS']);  
$PALMS    = trim($_POST['PALMS']); 
$LEGS = trim($_POST['LEGS']); 
$JAUNDICE = trim($_POST['JAUNDICE']);
$DEFORMITIES = trim($_POST['DEFORMITIES']); 
$HEART    = trim($_POST['HEART']);   
$LYMPHGLANDS    = trim($_POST['LYMPHGLANDS']);
$LUNGS    = trim($_POST['LUNGS']);
$HERPESZOSTER    = trim($_POST['HERPESZOSTER']);  
   

$ANYHOSPITALIZATION  = trim($_POST['ANYHOSPITALIZATION']); 
$DIABETESONE  = trim($_POST['DIABETESONE']); 
$BLEEDINGTHREE  = trim($_POST['BLEEDINGTHREE']); 
$TWINS  = trim($_POST['TWINS']); 
$REGNO  = trim($_POST['REGNO']); 
$ANCDYNAMICS  = trim($_POST['ANCDYNAMICS']); 
$SERIALNO = trim($_POST['SERIALNO']);
$USERINITIAL = trim($_POST['USERINITIAL']); 
$USERDESIGNATION    = trim($_POST['USERDESIGNATION']);   
$USERACCOUNT    = trim($_POST['USERACCOUNT']); 
  
$sql = "INSERT INTO antenatalcare (NTIHCNO, DATECREATED, CLIENTNAME, SCHOOLINGSTATUS, AGE, PHONECONTACT,HEALTHUNIT,
                                  
								   LCONE, CARDIACDISEASE, KIDNEYDISEASE, VILLAGE, PARISH, HYPERTENSION,TB,
								   CLIENTOCCUPATION, RELIGION, ASTHMA, TRIBE, STI, SICKLECELLS,MARITALSTATUS,EPILEPSYTWO, 
								   
								   BLEEDINGTWO, NEXTOFKIN, NEXTOFKINCONTACT, NEXTOFKINRELATIONSHIP, OCCUPATION, OPERATIONS,BLOODTRANSFUSION,
								   ADDRESS, REASONFORBLOODTRANSFUSION, GRAVIDA, PARA, ABORTIONS, FRACTURES,DC,ECTOPICPREGNANCY, 
								   
								   CAESAREANSECTION, VACUUMSXTRACTION, MENSES, AMOUNT, RETAINEDPLACENTA, PPH,METHODEVERUSED,
								   DISCONTINUEDATE, OPERATIONSONTHEUTERUS, CERVICALCIRCLAGE, REASONFORDISCONTINUE, REASONFORNEVERATTEMPT, SMOKING,
								   ALCOHOL,HEALTHOFTHEHUSBAND, FIRSTDAYOFLNMP, 
								   
								   EDD, GENSTATIONPERIOD, PREGNANCYCOMPLICATION, DIABETESTWO, HYPERTENSIONTWO, HOSPITALIZATIONTWO,HOSPITALIZATIONFOR,
								   BLEEDING, SICKLECELLSTWO, EPILEPSY, EXCESSIVEVOMITING, HUSBANDSHEALTH, FEVER,
								   DIARRHOEA,COUGH, WEIGHTLOSS, OTHERS,
								   
								   KNOWSTATUS, WANTTOTEST, HEIGHT, WEIGHT, BP, PULSE,TEMPERATURE,
								   NUTRITIONALSTATUS, WT, MUAC, ORALTHRUSH, ANAEMIA, TEETH,
								   EYES,NECK, NAILS, BREASTS, PALMS,LEGS, JAUNDICE, DEFORMITIES, HEART,LYMPHGLANDS, LUNGS, HERPESZOSTER,
								   
								   
								   ANCDYNAMICS,
								   ANYHOSPITALIZATION, DIABETESONE, BLEEDINGTHREE,TWINS, REGNO, AGE_GROUP, DATEOFBIRTH,
								   SERIALNO, USERINITIAL,  USERDESIGNATION, USERACCOUNT)
                             VALUES ('$REGNO', '$DATECREATED', '$CLIENTNAME', '$SCHOOLINGSTATUS', '$AGE', '$PHONECONTACT',
							 '$HEALTHUNIT',
							 '$LCONE', '$CARDIACDISEASE', '$KIDNEYDISEASE', '$VILLAGE', '$PARISH','$HYPERTENSION', '$TB', 
							 '$CLIENTOCCUPATION', '$RELIGION', '$ASTHMA', '$TRIBE', '$STI','$SICKLECELLS', '$MARITALSTATUS', '$EPILEPSYTWO',
							 
							 '$BLEEDINGTWO', '$NEXTOFKIN', '$NEXTOFKINCONTACT', '$NEXTOFKINRELATIONSHIP', '$OCCUPATION','$OPERATIONS', '$BLOODTRANSFUSION', 
							 '$ADDRESS', '$REASONFORBLOODTRANSFUSION', '$GRAVIDA', '$PARA', '$ABORTIONS','$FRACTURES', '$DC', '$ECTOPICPREGNANCY',
							 
							 '$CAESAREANSECTION', '$VACUUMSXTRACTION', '$MENSES', '$AMOUNT', '$RETAINEDPLACENTA','$PPH', '$METHODEVERUSED', 
							 '$DISCONTINUEDATE', '$OPERATIONSONTHEUTERUS', '$CERVICALCIRCLAGE', '$REASONFORDISCONTINUE', '$REASONFORNEVERATTEMPT','$SMOKING', 
							 '$ALCOHOL', '$HEALTHOFTHEHUSBAND', '$FIRSTDAYOFLNMP',
							 
							 '$EDD', '$GENSTATIONPERIOD', '$PREGNANCYCOMPLICATION', '$DIABETESTWO', '$HYPERTENSIONTWO','$HOSPITALIZATIONTWO', '$HOSPITALIZATIONFOR', 
							 '$BLEEDING', '$SICKLECELLSTWO', '$EPILEPSY', '$EXCESSIVEVOMITING', '$HUSBANDSHEALTH','$FEVER', 
							 '$DIARRHOEA', '$COUGH', '$WEIGHTLOSS', '$OTHERS',
							 
							 '$KNOWSTATUS', '$WANTTOTEST', '$HEIGHT', '$WEIGHT', '$BP','$PULSE', '$TEMPERATURE', 
							 '$NUTRITIONALSTATUS', '$WT', '$MUAC', '$ORALTHRUSH', '$ANAEMIA','$TEETH', 
							 '$EYES', '$NECK', '$NAILS', '$BREASTS',  '$PALMS', '$LEGS', '$JAUNDICE', '$DEFORMITIES',  '$HEART', '$LYMPHGLANDS', '$LUNGS', '$HERPESZOSTER',                
							 '$ANCDYNAMICS',
							 '$ANYHOSPITALIZATION','$DIABETESONE', '$BLEEDINGTHREE', '$TWINS', '$REGNO', '$AGE_GROUP', '$DATEOFBIRTH', 
							 '$SERIALNO', '$USERINITIAL', '$USERDESIGNATION', '$USERACCOUNT')";
							 

if (mysqli_query($conn, $sql)) {
    echo "New record created successfully";
	header("location:anc_home.php");
	exit();
} else {
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
}

mysqli_close($conn);
}
else{}
?>
